### PR TITLE
fix: fix stats and language tests

### PR DESCRIPTION
**Pull request by rickstaa**
Once last pull request that is needed to make the pre-commit script happy.

### CODE REVIEW

**Comment by developStorm** [comment]
I think this function call has too many arguments now:

https://github.com/developStorm/github-readme-stats/blob/master/api/top-langs.js#L46-L51

Could you fix this as well? Thanks!

**Comment by rickstaa** [comment]
@developStorm Very good catch I'm unsure why this was not caught as a conflict by git. Give me some time to see if other things were messed up.

**Comment by rickstaa** [comment]
I think for this pull request we are good I will now look at the earlier made pull request.

**Comment by developStorm** [comment]
I don't know where is that `parseArray(hide)` came from but it's not supposed to be there as well. `fetchTopLanguages` takes only 3 params:

```js
async function fetchTopLanguages(username, ownerAffiliations, exclude_repo = []) {
```

**Comment by rickstaa** [comment]
It is a bug that is present in the master branch I created a pull request for it see https://github.com/anuraghazra/github-readme-stats/pull/1451. I will include it in this pull request.

**Comment by rickstaa** [comment]
Included.

**Pull request merged**
